function Mountain_Range = mountainRangeInitialize(r0)

syms x y;
Bach_Peak = gaussianInitialize(r0(1,:),1.1);
Mount_Beethoven = gaussianInitialize(r0(2,:),2);
Haydin_Valley = gaussianInitialize(r0(3,:),1);
Vivaldi_Ridge = inversequadraticInitialize(r0(4,:),1.5);
Mount_Mozart = inversequadraticInitialize(r0(5,:),1.1);
Handel_Mountain = inversemultiquadraticInitialize(r0(6,:),1.9);
Schumann_Hill = inversemultiquadraticInitialize(r0(7,:),2);
Praetorius_Valley = multiquadraticInitialize(r0(8,:),.5);
Main_Plain = 1;

Mountain_Range =    2000*Bach_Peak + ...
                    2000*Mount_Beethoven + ...
                    -950*Haydin_Valley + ...
                    1000*Vivaldi_Ridge + ...
                    1500*Mount_Mozart + ...
                    3500*Handel_Mountain + ...
                    2000*Schumann_Hill + ...
                    200*Praetorius_Valley + ...
                    7000*Main_Plain;

end